### ISSUE TITLE
[Tracking issue]: Add nerdctl 2.0 compatibility

### ISSUE THREAD

**Issue by austinvazquez** [runfinch/common-tests#195]
### Description
This is a tracking issue for a list of tasks which need to be resolved to unblock nerdctl 2.0 integration.

finch-core https://github.com/runfinch/finch-core/pull/472 integrates nerdctl 2.0.2 as Finch's core container runtime on Finch on macOS and Windows platforms. (Note: Finch on Linux utilizes the platform's container runtime components)

### Integration test failures
- [x] #196
- [x] #206
- [x] [FAIL] Finch Core E2E Tests Compose down command [It] should stop compose services and delete volumes by specifying --volumes flag
- [x] [FAIL] Finch Core E2E Tests Compose down command [It] should stop compose services and delete volumes by specifying -v flag
- [x] #202
- [x] [FAIL] Finch Core E2E Tests Compose kill command [AfterEach] should not kill running containers with --signal TERM
- [x] [FAIL] Finch Core E2E Tests Compose kill command [AfterEach] should not kill running containers with -s SIGTERM
- [x] [FAIL] Finch Core E2E Tests Compose kill command [AfterEach] should not kill running containers with -s TERM
- [x] [FAIL] Finch Core E2E Tests Compose logs command [AfterEach] should show the logs with prefixes
- [x] [FAIL] Finch Core E2E Tests Compose logs command [AfterEach] should show the logs without prefixes
- [x] [FAIL] Finch Core E2E Tests Compose logs command [AfterEach] should show the logs with no color
- [x] [FAIL] Finch Core E2E Tests Compose logs command [AfterEach] should show the last line of the logs
- [x] [FAIL] Finch Core E2E Tests Compose logs command [AfterEach] should show the logs with timestamp with no prefixes and no color [flag --timestamps]
- [x] [FAIL] Finch Core E2E Tests Compose logs command [AfterEach] should show the logs with timestamp with no prefixes and no color [flag -t]
- [x] #200
- [x] #205
- [x] #198
- [x] #209

**Comment by austinvazquez** [comment]
Deduped compose kill command and compose logs command integration test failures to #202.

**Comment by austinvazquez** [comment]
Deduped compose down command integration test failures to #206

**Comment by austinvazquez** [comment]
Release PR https://github.com/runfinch/common-tests/pull/189

**Comment by austinvazquez** [comment]
v0.9.0 tag has been created! 🥳
